### ISSUE TITLE
Multiple Images

### ISSUE THREAD

**Issue by mariob316** [judepereira/android-multitouch#1]
How can this be changed to support multiple images?

**Comment by judepereira** [comment]
Use one ImageView for every image.

Use the same code now, and identify which ImageView was tapped. Make that
the current active ImageView object and manipulate it.

Store the other ImageViews along with their respective matrices in an array
list or something.

Let me know if you need a more detailed explanation.

**Comment by mariob316** [comment]
The problem is the ImageViews use fill_parent, so the touch event never reaches the second image. If i switch to wrap_content a boundary the size of the image is created around each image.

**Comment by judepereira** [comment]
Have you tried to set the ImageView's size explicitly? In my case, this
works just fine.

**Comment by mariob316** [comment]
I did try, but it creates a boundary around the image. I will continue to try some different ways, if not i will switch to using a surfaceview.

Thanks!

**Comment by judepereira** [comment]
Try adding android:scaleType="centerCrop" and android:cropToPadding="true"
to your ImageViews. That solved the padding problem for me.

**Comment by mariob316** [comment]
changing the scaletype disabled all functionality. It needs to be Matrix for it to work, in onTouch() we are changing the matrix and resetting it.

**Comment by judepereira** [comment]
It doesn't need to be matrix. Matrix implies something else actually.

I have it working with multiple ImageViews very well here.

Changing that shouldn't have broken functionality. Do you still see the
ImageViews?

**Comment by mariob316** [comment]
Hmmm, it broke for me :/ I see the images but cannot scale/rotate them. Would you be able to upload your new multiple image on a new branch in this git or upload to some sort of dropbox or google drive? Would be awesome!!

**Comment by judepereira** [comment]
I don't have a new one dedicated for that. I've used this concept in two of
my apps developed for a company.

**Comment by GauravMandlik** [comment]
i working with your given code it really work fine but can i put a multiple images on That and each image is move on screen on touch is that possible.... so please give me some suggestion on that .....Thanks
